### ISSUE TITLE
DeepKE with Transformers >= 4.4.2

### ISSUE THREAD

**Issue by khairunnisaor** [zjunlp/DeepKE#184]
Hi, 
I want to use LightNER for Transformers >= 4.4.2 since the pre-trained models are supported in the higher version of Transformers. 
However, the `modeling_bart.py` in DeepKE is adapted on Transformers 3.4.0. I tried to adapt your customization for LightNER on the new `modeling_bart.py` from Transformers 4.4.2 but encountered some problems.

Do you have any advice on how I can implement new models with LightNER and Transformers 3.4.0?

Thank you in advance!

**Comment by Flow3rDown** [comment]
Hi,
Since `modeling_bart.py` are different in Transformers 3.4.0 and Transformers 4.4.2, you need to modify the `modeling_bart.py` to adapt the `Pluggable Guidance Layer` in LightNER. A reference example is [UnifiedSKG](https://github.com/hkunlp/unifiedskg/blob/main/models/prompt/modeling_bart.py), they adapt the prefix-tuning in more higher version than Transformers 3.4.0.

**Comment by khairunnisaor** [comment]
Thank you! I will take a look at your reference :)
