### ISSUE TITLE
分布训练的错误，现在只有一张3090报错

### ISSUE THREAD

**Issue by sunyongdi** [zjunlp/DeepKE#317]
**Describe the bug**
> A clear and concise description of what the bug is.

RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the `forward` function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes. or try to use _set_static_graph() as a workaround if this module graph does not change during training loop.2) Reused parameters in multiple reentrant backward passes. For example, if you use multiple `checkpoint` functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases in default. You can try to use _set_static_graph() as a workaround if your module graph does not change over iterations.
Parameter at index 55 has been marked as ready twice. This means that multiple autograd engine  hooks have fired for this particular parameter during this iteration. You can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print parameter names for further debugging.

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by xxupiano** [comment]
请问这是那个任务和场景的代码？

**Comment by sunyongdi** [comment]
LoRA微调ChatGLM
执行脚本如下：
output_dir='lora/chatglm-6b'
mkdir -p ${output_dir}
CUDA_VISIBLE_DEVICES="0" torchrun --nproc_per_node=1 --master_port=1331 src/finetune.py \
    --do_train --do_eval \
    --model_name_or_path '/root/sunyd/model_hub/chatglm-6b' \
    --model_name 'chatglm' \
    --train_file 'data/train.json' \
    --output_dir=${output_dir}  \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 8 \
    --preprocessing_num_workers 8 \
    --num_train_epochs 10 \
    --learning_rate 1e-5 \
    --weight_decay 5e-4 \
    --adam_beta2 0.95 \
    --optim "adamw_torch" \
    --max_source_length 512 \
    --max_target_length 256 \
    --val_set_size 1000 \
    --evaluation_strategy "epoch" \
    --save_strategy "epoch" \
    --save_total_limit 10 \
    --lora_r 8 \
    --lora_alpha 32 \
    --lora_dropout 0.1 \
    --max_memory_MB 24000 \
    --fp16 \
    | tee ${output_dir}/train.log \
    2> ${output_dir}/train.err

**Comment by gz927cool** [comment]
@sunyongdi 您好，我在3090上LoRA微调ChatGLM遇到了相同的问题，请教一下您是如何解决此问题的？

**Comment by pillow-xi** [comment]
> 
您好，能详细提供您的报错信息嘛

**Comment by sunyongdi** [comment]
torchrun 改成python就好了

**Comment by sunyongdi** [comment]
torchrun 将这个修改成python就好了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月9日(星期三) 上午9:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***@***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zjunlp/DeepKE] 分布训练的错误，现在只有一张3090报错 (Issue #317)





 
@sunyongdi 您好，我在3090上LoRA微调ChatGLM遇到了相同的问题，请教一下您是如何解决此问题的？

**Comment by gz927cool** [comment]
您好,这是我执行LoRA微调ChatGLM时的环境:
cat /etc/os-release
&nbsp; &nbsp; NAME="Ubuntu"
&nbsp; &nbsp; VERSION="20.04.6 LTS (Focal Fossa)
sys.version
&nbsp; &nbsp; '3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0]'
torch.__version__
&nbsp; &nbsp; '1.13.0+cu117'
torch.version.cuda
&nbsp; &nbsp; '11.7'


下面是遭遇的报错完整信息:
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run
python -m bitsandbytes
&nbsp;and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/guozhi/miniconda3/envs/deepke-llm/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda112.so
/home/guozhi/miniconda3/envs/deepke-llm/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: /home/guozhi/miniconda3/envs/deepke-llm did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
&nbsp; warn(msg)
/home/guozhi/miniconda3/envs/deepke-llm/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/tmp/torchelastic_jwmhzzsb/none_bz40ol0f/attempt_0/0/error.json')}
&nbsp; warn(msg)
/home/guozhi/miniconda3/envs/deepke-llm/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/usr/local/cuda/lib64/libcudart.so.11.0'), PosixPath('/usr/local/cuda/lib64/libcudart.so')}.. We'll flip a coin and try one of these, in order to fail forward.
Either way, this might cause trouble in the future:
If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
&nbsp; warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so.11.0
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 112
CUDA SETUP: Loading binary /home/guozhi/miniconda3/envs/deepke-llm/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda112.so...
08/10/2023 14:27:00 - INFO - __main__ - Start Time: 2023:08:10 14:27:00
08/10/2023 14:27:00 - INFO - __main__ - model_args:ModelArguments(model_name_or_path='models/chatglm-6b', model_name='chatglm', trust_remote_code=True, use_auth_token=False)
data_args:DataArguments(train_file='data/train.json', valid_file=None, max_source_length=512, max_target_length=256, cutoff_len=512, val_set_size=1000, prompt_template_name='alpaca', preprocessing_num_workers=8, pad_to_max_length=False, ignore_pad_token_for_loss=True, train_on_inputs=False)
training_args:TrainingArguments(
_n_gpu=1,
adafactor=False,
adam8bit=False,
adam_beta1=0.9,
adam_beta2=0.95,
adam_epsilon=1e-08,
auto_find_batch_size=False,
bf16=False,
bf16_full_eval=False,
bits=16,
cache_dir=None,
data_seed=None,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_pin_memory=True,
ddp_backend=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=True,
double_quant=True,
eval_accumulation_steps=None,
eval_delay=0,
eval_steps=None,
evaluation_strategy=epoch,
fp16=True,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'fsdp_min_num_params': 0, 'xla': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
full_finetune=False,
generation_config=GenerationConfig {
&nbsp; "max_new_tokens": 256,
&nbsp; "transformers_version": "4.30.2"
}
,
generation_max_length=None,
generation_num_beams=None,
gradient_accumulation_steps=8,
gradient_checkpointing=True,
greater_is_better=False,
group_by_length=True,
half_precision_backend=auto,
hub_model_id=None,
hub_private_repo=False,
hub_strategy=every_save,
hub_token=<HUB_TOKEN&gt;,
ignore_data_skip=False,
include_inputs_for_metrics=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=1e-05,
length_column_name=length,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=lora/chatglm-6b/runs/Aug10_14-27-00_Nist-PC,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=10,
logging_strategy=steps,
lora_alpha=32.0,
lora_dropout=0.1,
lora_r=8,
lora_target_modules=['query_key_value'],
loss_scale=1.0,
lr_scheduler_type=linear,
max_grad_norm=1.0,
max_memory_MB=24000,
max_steps=-1,
metric_for_best_model=loss,
mp_parameters=,
no_cuda=False,
num_train_epochs=10.0,
optim=adamw_torch,
optim_args=None,
output_dir=lora/chatglm-6b,
overwrite_output_dir=False,
past_index=-1,
per_device_eval_batch_size=4,
per_device_train_batch_size=4,
predict_with_generate=False,
prediction_loss_only=False,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN&gt;,
quant_type=nf4,
ray_scope=last,
remove_unused_columns=False,
report_to=[],
resume_from_checkpoint=None,
run_name=lora/chatglm-6b,
save_on_each_node=False,
save_safetensors=False,
save_steps=500,
save_strategy=epoch,
save_total_limit=10,
seed=42,
sharded_ddp=[],
skip_memory_metrics=True,
sortish_sampler=False,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
use_ipex=False,
use_legacy_prediction_loop=False,
use_mps_device=False,
warmup_ratio=0.0,
warmup_steps=0,
weight_decay=0.0005,
xpu_backend=None,
)


08/10/2023 14:27:00 - INFO - __main__ - model_class:<class 'transformers.models.auto.modeling_auto.AutoModel'&gt;
tokenizer_class:<class 'transformers.models.auto.tokenization_auto.AutoTokenizer'&gt;
trainer_class:<class 'transformers.trainer_seq2seq.Seq2SeqTrainer'&gt;


loading base model models/chatglm-6b...
08/10/2023 14:27:00 - INFO - __main__ - compute_dtype:torch.float16
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:05<00:00,&nbsp; 1.38it/s]
adding LoRA modules...
trainable params: 3,670,016 || all params: 6,176,956,416 || trainable%: 0.05941463324063059
08/10/2023 14:27:13 - INFO - __main__ - coll_fn:<function preprocess_chatglm at 0x7f3b86407520&gt;
data_collator:DataCollatorForSeq2Seq(tokenizer=ChatGLMTokenizer(name_or_path='models/chatglm-6b', vocab_size=130344, model_max_length=1000000000000000019884624838656, is_fast=False, padding_side='left', truncation_side='right', special_tokens={'bos_token': '<sop&gt;', 'eos_token': '<eop&gt;', 'unk_token': '<unk&gt;', 'pad_token': '<pad&gt;', 'mask_token': '[MASK]'}, clean_up_tokenization_spaces=True), model=None, padding=True, max_length=None, pad_to_multiple_of=8, label_pad_token_id=-100, return_tensors='pt')
prompter:<utils.prompter.Prompter object at 0x7f3b84146830&gt;


08/10/2023 14:27:13 - INFO - __main__ - BOS:130004,<sop&gt;&nbsp; &nbsp; &nbsp; &nbsp; EOS:130005,<eop&gt;&nbsp; &nbsp; &nbsp; &nbsp; PAD:3,<pad&gt;
torch.float16 6173286400 0.9994058536675937
torch.float32 3670016 0.0005941463324063059
08/10/2023 14:27:13 - INFO - __main__ - *** Train ***
args.resume_from_checkpoint None
&nbsp; 0%|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; | 0/1250 [00:00<?, ?it/s]/home/guozhi/miniconda3/envs/deepke-llm/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:731: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at ../torch/csrc/utils/tensor_new.cpp:230.)
&nbsp; tensor = as_tensor(value)
Traceback (most recent call last):
&nbsp; File "/home/guozhi/project/DeepKE/example/llm/InstructKGC/src/finetune.py", line 290, in <module&gt;
&nbsp; &nbsp; main()
&nbsp; File "/home/guozhi/project/DeepKE/example/llm/InstructKGC/src/finetune.py", line 285, in main
&nbsp; &nbsp; train(model_args, data_args, training_args, args)
&nbsp; File "/home/guozhi/project/DeepKE/example/llm/InstructKGC/src/finetune.py", line 240, in train
&nbsp; &nbsp; train_result = trainer.train(resume_from_checkpoint=args.resume_from_checkpoint)
&nbsp; File "/home/guozhi/miniconda3/envs/deepke-llm/lib/python3.10/site-packages/transformers/trainer.py", line 1645, in train
&nbsp; &nbsp; return inner_training_loop(
&nbsp; File "/home/guozhi/miniconda3/envs/deepke-llm/lib/python3.10/site-packages/transformers/trainer.py", line 1938, in _inner_training_loop
&nbsp; &nbsp; tr_loss_step = self.training_step(model, inputs)
&nbsp; File "/home/guozhi/miniconda3/envs/deepke-llm/lib/python3.10/site-packages/transformers/trainer.py", line 2770, in training_step
&nbsp; &nbsp; self.accelerator.backward(loss)
&nbsp; File "/home/guozhi/miniconda3/envs/deepke-llm/lib/python3.10/site-packages/accelerate/accelerator.py", line 1851, in backward
&nbsp; &nbsp; self.scaler.scale(loss).backward(**kwargs)
&nbsp; File "/home/guozhi/miniconda3/envs/deepke-llm/lib/python3.10/site-packages/torch/_tensor.py", line 487, in backward
&nbsp; &nbsp; torch.autograd.backward(
&nbsp; File "/home/guozhi/miniconda3/envs/deepke-llm/lib/python3.10/site-packages/torch/autograd/__init__.py", line 197, in backward
&nbsp; &nbsp; Variable._execution_engine.run_backward(&nbsp; # Calls into the C++ engine to run the backward pass
&nbsp; File "/home/guozhi/miniconda3/envs/deepke-llm/lib/python3.10/site-packages/torch/autograd/function.py", line 267, in apply
&nbsp; &nbsp; return user_fn(self, *args)
&nbsp; File "/home/guozhi/miniconda3/envs/deepke-llm/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 157, in backward
&nbsp; &nbsp; torch.autograd.backward(outputs_with_grad, args_with_grad)
&nbsp; File "/home/guozhi/miniconda3/envs/deepke-llm/lib/python3.10/site-packages/torch/autograd/__init__.py", line 197, in backward
&nbsp; &nbsp; Variable._execution_engine.run_backward(&nbsp; # Calls into the C++ engine to run the backward pass
RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the `forward` function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes. or try to use _set_static_graph() as a workaround if this module graph does not change during training loop.2) Reused parameters in multiple reentrant backward passes. For example, if you use multiple `checkpoint` functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases in default. You can try to use _set_static_graph() as a workaround if your module graph does not change over iterations.
Parameter at index 55 has been marked as ready twice. This means that multiple autograd engine&nbsp; hooks have fired for this particular parameter during this iteration. You can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print parameter names for further debugging.
&nbsp; 0%|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; | 0/1250 [00:02<?, ?it/s]
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 718759) of binary: /home/guozhi/miniconda3/envs/deepke-llm/bin/python3.10
Traceback (most recent call last):
&nbsp; File "/home/guozhi/miniconda3/envs/deepke-llm/bin/torchrun", line 8, in <module&gt;
&nbsp; &nbsp; sys.exit(main())
&nbsp; File "/home/guozhi/miniconda3/envs/deepke-llm/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
&nbsp; &nbsp; return f(*args, **kwargs)
&nbsp; File "/home/guozhi/miniconda3/envs/deepke-llm/lib/python3.10/site-packages/torch/distributed/run.py", line 762, in main
&nbsp; &nbsp; run(args)
&nbsp; File "/home/guozhi/miniconda3/envs/deepke-llm/lib/python3.10/site-packages/torch/distributed/run.py", line 753, in run
&nbsp; &nbsp; elastic_launch(
&nbsp; File "/home/guozhi/miniconda3/envs/deepke-llm/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
&nbsp; &nbsp; return launch_agent(self._config, self._entrypoint, list(args))
&nbsp; File "/home/guozhi/miniconda3/envs/deepke-llm/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
&nbsp; &nbsp; raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:&nbsp;
============================================================
src/finetune.py FAILED
------------------------------------------------------------
Failures:
&nbsp; <NO_OTHER_FAILURES&gt;
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
&nbsp; time&nbsp; &nbsp; &nbsp; : 2023-08-10_14:27:19
&nbsp; host&nbsp; &nbsp; &nbsp; : Nist-PC
&nbsp; rank&nbsp; &nbsp; &nbsp; : 0 (local_rank: 0)
&nbsp; exitcode&nbsp; : 1 (pid: 718759)
&nbsp; error_file: <N/A&gt;
&nbsp; traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zjunlp/DeepKE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月9日(星期三) 晚上6:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zjunlp/DeepKE] 分布训练的错误，现在只有一张3090报错 (Issue #317)





 
您好，能详细提供您的报错信息嘛

**Comment by gz927cool** [comment]
好的，改成python直接运行并执行成功，感谢您的指导




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zjunlp/DeepKE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月9日(星期三) 晚上6:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zjunlp/DeepKE] 分布训练的错误，现在只有一张3090报错 (Issue #317)





 
torchrun 改成python就好了
